import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { App, ConfigProvider } from "antd";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

const customTheme = {
  components: {
    Table: {
      colorBgContainer: "#ffffff",
      colorBorderSecondary: "#cfcfcf",
      headerBg: "#eeeeee",
      borderRadiusLG: 0,
    },
    Button: {
      colorBgTextActive: "#F52727",
    },
  },
};

export const metadata: Metadata = {
  title: "Book Store App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased bg-gray-100`}
      >
        <ToastContainer />
        <App>
          <ConfigProvider theme={customTheme}>{children}</ConfigProvider>
        </App>
      </body>
    </html>
  );
}